public static class ForgetFractalData {
	public static readonly string[] DefaultIgnoredModules = new[] {
		"Forget Fractal",
		"+",
		"14",
		"8",
		"Again",
		"A>N<D",
		"Bamboozling Time Keeper",
		"Bitwise Oblivion",
		"Black Arrows",
		"Brainf---",
		"Busy Beaver",
		"Castor",
		"Concentration",
		"Cube Synchronization",
		"Damocles Lumber",
		"Don't Touch Anything",
		"Doomsday Button",
		"Duck Konundrum",
		"Floor Lights",
		"Forget Any Color",
		"Forget Enigma",
		"Forget Everything",
		"Forget It Not",
		"Forget Maze Not",
		"Forget Me Later",
		"Forget Me Maybe",
		"Forget Me Not",
		"Forget Morse Not",
		"Forget Our Voices",
		"Forget Perspective",
		"Forget The Colors",
		"Forget Us Not",
		"Forget This",
		"Forget Them All",
		"Gemory",
		"HyperForget",
		"Iconic",
		"ID Exchange",
		"Keypad Directionality",
		"Kugelblitz",
		"OmegaDestroyer",
		"OmegaForget",
		"Organization",
		"Out of Time",
		"Password Destroyer",
		"Pollux",
		"Purgatory",
		"Red Light Green Light",
		"Remember Simple",
		"Remembern't Simple",
		"RPS Judging",
		"Security Council",
		"Shoddy Chess",
		"Simon Forgets",
		"Simon Sonundrum",
		"Simon's Stages",
		"Soulscream",
		"Soulsong",
		"Souvenir",
		"Squad's Shadow",
		"Tallordered Keys",
		"Tetrahedron",
		"The Board Walk",
		"The Grand Prix",
		"The Time Keeper",
		"The Twin",
		"The Troll",
		"The Very Annoying Button",
		"Timing is Everything",
		"Top 10 Numbers",
		"Turn The Key",
		"Twister",
		"Ultimate Custom Night",
		"Ultra Custom Night",
		"Whiteout",
		"X",
		"Y",
		"Zener Cards",
		"[BIG SHOT]",
		"Übermodule",
	};
}
